from setuptools import setup, find_packages
import codecs
import os

VERSION = '0.0.1'
DESCRIPTION = 'A Python package for PII detection and classification'
LONG_DESCRIPTION = """
# Privacy Sherlock - PII Detection and Classification

This Python package helps detect Personally Identifiable Information (PII) in various data sources (e.g., MySQL, Amazon S3, MongoDB) and classifies them into categories (financial, personal, etc.). It supports PII risk assessment and visualization of the data.

## Features
- Detects PII using regular expressions.
- Classifies PII into categories like financial and personal.
- Supports data ingestion from MySQL, Amazon S3, and MongoDB.
- Provides a risk score based on the detected PII.
- Visualizes PII distribution using Plotly.
"""

# Setting up
setup(
    name="PrivacySherlock",
    version=VERSION,
    author="Tosif Ansari",
    author_email="tosif.ansari@example.com",  # Update with your actual email
    description=DESCRIPTION,
    long_description_content_type="text/markdown",
    long_description=LONG_DESCRIPTION,
    packages=find_packages(),
    install_requires=[
        'altair==5.4.1',
        'annotated-types==0.7.0',
        'anyio==4.4.0',
        'attrs==24.2.0',
        'azure-core==1.30.2',
        'blinker==1.8.2',
        'blis==0.7.11',
        'boto3==1.35.13',
        'botocore==1.35.13',
        'cachetools==5.5.0',
        'catalogue==2.0.10',
        'certifi==2024.8.30',
        'cffi==1.17.1',
        'charset-normalizer==3.3.2',
        'click==8.1.7',
        'cloudpathlib==0.19.0',
        'colorama==0.4.6',
        'confection==0.1.5',
        'cryptography==43.0.1',
        'cymem==2.0.8',
        'distro==1.9.0',
        'dnspython==2.6.1',
        'easyocr==1.7.1',
        'exceptiongroup==1.2.2',
        'filelock==3.15.4',
        'fsspec==2024.9.0',
        'gitdb==4.0.11',
        'GitPython==3.1.43',
        'groq==0.11.0',
        'h11==0.14.0',
        'htbuilder==0.6.2',
        'httpcore==1.0.5',
        'httpx==0.27.2',
        'idna==3.8',
        'imageio==2.35.1',
        'Jinja2==3.1.4',
        'jmespath==1.0.1',
        'jsonschema==4.23.0',
        'jsonschema-specifications==2023.12.1',
        'langcodes==3.4.0',
        'language_data==1.2.0',
        'lazy_loader==0.4',
        'linecache2==1.0.0',
        'marisa-trie==1.2.0',
        'markdown-it-py==3.0.0',
        'MarkupSafe==2.1.5',
        'mdurl==0.1.2',
        'more-itertools==10.5.0',
        'mpmath==1.3.0',
        'murmurhash==1.0.10',
        'mysql==0.0.3',
        'mysql-connector-python==9.0.0',
        'mysql-connector-python-rf==2.2.2',
        'mysqlclient==2.2.4',
        'narwhals==1.6.2',
        'networkx==3.3',
        'ninja==1.11.1.1',
        'numpy==1.26.4',
        'opencv-python-headless==4.10.0.84',
        'packaging==24.1',
        'pandas==2.2.2',
        'pdfminer.six==20231228',
        'pdfplumber==0.11.4',
        'phonenumbers==8.13.45',
        'pillow==10.4.0',
        'plotly==5.24.0',
        'preshed==3.0.9',
        'presidio_analyzer==2.2.355',
        'presidio_anonymizer==2.2.355',
        'protobuf==5.28.0',
        'pyarrow==17.0.0',
        'pyclipper==1.3.0.post5',
        'pycparser==2.22',
        'pycryptodome==3.20.0',
        'pydantic==2.9.1',
        'pydantic_core==2.23.3',
        'pydeck==0.9.1',
        'Pygments==2.18.0',
        'pymongo==4.8.0',
        'pypdfium2==4.30.0',
        'pytesseract==0.3.13',
        'python-bidi==0.6.0',
        'python-dateutil==2.9.0.post0',
        'pytz==2024.1',
        'PyYAML==6.0.2',
        'referencing==0.35.1',
        'regex==2024.7.24',
        'requests==2.32.3',
        'requests-file==2.1.0',
        'rich==13.8.0',
        'rpds-py==0.20.0',
        's3transfer==0.10.2',
        'scikit-image==0.24.0',
        'scipy==1.14.1',
        'shapely==2.0.6',
        'shellingham==1.5.4',
        'six==1.16.0',
        'smart-open==7.0.4',
        'smmap==5.0.1',
        'sniffio==1.3.1',
        'spacy==3.7.6',
        'spacy-legacy==3.0.12',
        'spacy-loggers==1.0.5',
        'srsly==2.4.8',
        'st-annotated-text==4.0.1',
        'streamlit==1.38.0',
        'sympy==1.13.2',
        'tenacity==8.5.0',
        'thinc==8.2.5',
        'tifffile==2024.8.30',
        'tldextract==5.1.2',
        'toml==0.10.2',
        'torch==2.4.1',
        'torchvision==0.19.1',
        'tornado==6.4.1',
        'tqdm==4.66.5',
        'traceback2==1.4.0',
        'typer==0.12.5',
        'typing_extensions==4.12.2',
        'tzdata==2024.1',
        'unittest2==1.1.0',
        'urllib3==2.2.2',
        'wasabi==1.1.3',
        'watchdog==4.0.2',
        'weasel==0.4.1',
        'wrapt==1.16.0',
    ],
    keywords=['python', 'pii detection', 'privacy', 'data privacy', 'pii', 'data classification'],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.6',
)
